# Generated by Django 3.2 on 2021-04-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetoLiver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='reto',
            name='phone',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
